version: "3.9"
services:
  service:
    image: openjdk:17-jdk
    ports:
      - 8080:8080
    volumes:
      - ../tictactoe-service/build/libs/tictactoe-service.jar:/service.jar
    entrypoint: ["java", "-jar", "-Dspring.profiles.active=local", "service.jar"]
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://service:8080/health || exit 1"]
      interval: 3s
      timeout: 1s
      retries: 10
