spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

server:
  error:
    include-message: always
